### ISSUE TITLE
custom:为侧边目录限制最大高度并增加滚动条

### ISSUE THREAD

**Issue by lcdyk** [nineya/halo-theme-dream2.0#20]
### 你当前使用的 Halo 版本

2.6.1

### 你当前使用的 Dream 版本

1.0.2

### 描述一下此特性

当目录超过屏幕长度时，给目录增加一个滚动条，不然超过屏幕部分的目录不可选择了。

**Comment by nineya** [comment]
可通过定制主题内嵌css的方式实现

**Comment by nineya** [comment]
**配置方法：** 内嵌CSS方式实现自定义
**配置路径：** 外观->主题设置->定制主题->内嵌CSS
**配置内容：**
配置框中添加如下CSS代码，代码中限制的最大高度为 `500px`，可根据需要调整。
```css
.widget .card-content.toc-content {
    max-height: 500px;
    overflow-y: auto;
}
```
