### ISSUE TITLE
custom: 是否能直接显示全部目录 , 或者提供选项来切换两种目录

### ISSUE THREAD

**Issue by Sakura-LF** [nineya/halo-theme-dream2.0#40]
### 你当前使用的 Dream 版本

最新版

### 描述一下此定制化内容

大佬 , 目录能直接显示所有吗 , 默认会隐藏一级标题之后的 , 想要直接显示所有目录 , 能否提供一个选项来切换两种目录显示方法
![image](https://github.com/nineya/halo-theme-dream2.0/assets/80140609/7889b559-2166-47d0-aadf-db6ad744ef99)

**Comment by nineya** [comment]
**配置方法：** 内嵌CSS方式实现自定义
**配置路径：** 外观->主题设置->定制主题->内嵌CSS
**配置内容：**
配置框中添加如下CSS代码
```css
.menu-list>li>a:not(.is-active)+.menu-list {
    display: block;
}
```
