### ISSUE TITLE
custom:自定义标签Widget模块和标签页的标签颜色

### ISSUE THREAD

**Issue by Arvinsyt** [nineya/halo-theme-dream2.0#52]
### 是什么 Halo 版本出现了此问题？

2.10.0

### 使用的 Dream 版本是多少？

1.1.1

### 在线博客地址

https://blog.yuanyu.ac.cn/tags

### BUG 内容

<img width="443" alt="20231016203939595" src="https://github.com/nineya/halo-theme-dream2.0/assets/133661228/ac190161-8b11-440f-a94c-bb711cde4dfb">
<img width="1004" alt="20231016204005488" src="https://github.com/nineya/halo-theme-dream2.0/assets/133661228/a0272582-6dbb-4c94-bd41-b11c167f96af">
添加上面的代码后，修改的只是右下角的标签字体颜色，中间的文章标签字体颜色仍然没有改变，请问怎么修改中间的标签字体颜色？

**Comment by nineya** [comment]
```css
.tags-field .tags .tag {
    background-color: var(--bg-c) !important;
    color: var(--dark-c) !important;
}
.tags-field .tags .tag.is-grey {
    background: var(--bg-e) !important;
    color: rgba(255,255,255,.8) !important;
}
```
